version: '3'
services:
  mysql8:
    image: "mysql:8"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=mobetize
      - MYSQL_PASSWORD=mobetize
      - MYSQL_DATABASE=nona
    ports:
      - "3306:3306"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  nona: 
    image: "adoptopenjdk:11-jre-openj9"
    ports:
      - "8080:8080"
    depends_on: 
      - "mysql8"
    volumes:
      - ./nona:/opt/app
    command: ["bash","-c","cd /opt/app && sleep 30 && MYSQL_USERNAME=mobetize MYSQL_PASSWORD=mobetize java -jar /opt/app/nona.jar"]
  